### ISSUE TITLE
Transcribe OGCIO S17 document into Metanorma format

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/hk-ogcio-infosec-docs#1]
https://www.ogcio.gov.hk/en/our_work/information_cyber_security/government/doc/S17.pdf

**Comment by ronaldtse** [comment]
For @anermina or @manuel489

**Comment by manuelfuenmayor** [comment]
I'm working on this one. Thanks!

**Comment by ronaldtse** [comment]
Completed. Thanks!
