### ISSUE TITLE
Fix docker.yml workflow to actually build the documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/hk-ogcio-infosec-docs#16]
Somehow, during the build step, `make` is unable to find any files in `sources/`?! This is preventing artifacts being generated, and therefore the deploy step fails.

https://github.com/metanorma/hk-ogcio-infosec-docs/runs/425444641?check_suite_focus=true
<img width="905" alt="Screen Shot 2020-02-05 at 12 21 04 AM" src="https://user-images.githubusercontent.com/11865/73764126-66554500-47ad-11ea-887a-92e0e940f7ae.png">

This line:
```
# this is `make clean`
rm -rf documents documents.{html,rxl} published *_images sources/*.{}
```

Should have been:
```
# on my local when running `make clean`
rm -rf documents documents.{html,rxl} published *_images sources/*.{doc,html,pdf,rxl,xml}
```

I couldn't find out what's going on, perhaps someone with a better eye can see what's wrong in the Makefile! Ping @CAMOBAP795 .

**Comment by CAMOBAP** [comment]
Done
