### ISSUE TITLE
Convert all OGCIO Infosec documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/hk-ogcio-infosec-docs#4]
Link: https://www.ogcio.gov.hk/en/our_work/information_cyber_security/government/

**Comment by anermina** [comment]
SM01 and SM04 are added in #11 
S17 and G3 are already converted and pushed. 
@manuel489 is assigned to the other 3 issues/Infosec documents.

**Comment by ronaldtse** [comment]
Completed in #11 and #12. Closing.
